language: python
python: '3.5'
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=clean
    - TOXENV=check
    - TOXENV=flake8
    - TOXENV=py27
    - TOXENV=report
before_install:
  - python --version
install:
  - pip install tox coveralls
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: always
    on_failure: always
